### ISSUE TITLE
Mongoid::Errors::DocumentNotFound if I have the same value slugs in different locales for different documents

### ISSUE THREAD

**Issue by nazarok** [digitalplaywright/mongoid-slug#175]
for example:

article1._slugs_t = { "ru" => ["test-1"], "uk" => ["test"] }
article2._slugs_t = { "ru" => ["test"], "uk" => ["test-1"] }

I18n.locale = :uk
Article.find('test-1') # => Mongoid::Errors::DocumentNotFound

**Comment by dblock** [comment]
@nazarok Bump, is this an issue that was fixed in mongoid? Something else?

**Comment by nazarok** [comment]
this bug is reproduced in mongoid-4.0.2
this error is absent in mongoid-5.0.0
