### ISSUE TITLE
Slugs do not initialize

### ISSUE THREAD

**Issue by vanboom** [digitalplaywright/mongoid-slug#177]
When mongoid-slug is added to an existing application, the Model.slugs field is blank until every document is re-saved.  

Suggestion:  have a rake task or some default logic in mongoid-slug that will handle this initial case.  Applications with large data sets that have business logic around "updated_at" may not want to re-save each instance to get the slug behavior. 

Thanks!

**Comment by pencilcheck** [comment]
Yea, would be nice to have it generated initially for existing documents, was confused why it didn't work.
:+1:

**Comment by tbbooher** [comment]
agreed, at least for me .  . . very grateful for this issue.

**Comment by anuja-joshi** [comment]
@digitalplaywright  I am looking into this issue and wrote a rake task that will set slug for existing records, to load this task into **Rails** we need to use `Rails::Railtie`, that will be Rails specific. Do you want this task to support any other frameworks ?

**Comment by simi** [comment]
@anuja-joshi You can add just task file and inform users to load that rake tasks file into their rake stack.

**Comment by dblock** [comment]
A rake task was added in https://github.com/digitalplaywright/mongoid-slug/commit/8abb60d6c263f532e51b1ea064b88e6df25b2658.
