### ISSUE TITLE
Strange problem with indexes and notablescan

### ISSUE THREAD

**Issue by ngw** [digitalplaywright/mongoid-slug#178]
Hi, I've set notablescan to true in my MongoDB configuration and I have a very strange "crash" when querying by slug one of my models

Here is my class (stripped down of what I think is not useful)
https://gist.github.com/ngw/ae9c236980b8a2353fe8

And here is the error:
Moped::Errors::QueryFailure: The operation: #<Moped::Protocol::Query
  @length=99
  @request_id=2
  @response_to=0
  @op_code=2004
  @flags=[:slave_ok]
  @full_collection_name="readom_development.entities"
  @skip=0
  @limit=1
  @selector={"_slugs"=>{"$in"=>["america"]}}
  @fields=nil>
failed with error 17007: "Unable to execute query: error processing query: ns=readom_development.entities limit=1 skip=0\nTree: _slugs $in [ \"america\" ]\nSort: {}\nProj: {}\n No query solutions"

The instruction is a very simple Entity.find('america') so I don't know what's happening here...
I've deleted and recreated all indexes already.

Any suggestion?

**Comment by digitalplaywright** [comment]
Since it might be completely valid that a slug is non-existant we can unfortuantely not add in this validation. However, you can validate that the _slugs field exists on your own model if this is desirable in your app.
