### ISSUE TITLE
mongoid 5 compatibility

### ISSUE THREAD

**Issue by deepredsky** [digitalplaywright/mongoid-slug#185]
Seems like mongoid 5 will soon be released. 
https://github.com/mongoid/mongoid/commit/507d7a794f6edd5f2b1a2b86c922340f3cf7d9c2

Is there any plan or work in progress to update mongoid-slug to make it compatible with mongoid 5?

**Comment by sahin** [comment]
+1

**Comment by deepredsky** [comment]
without paranoid document, it works with just few changes.

https://github.com/digitalplaywright/mongoid-slug/compare/master...deepredsky:feature/mongoid-5

**Comment by digitalplaywright** [comment]
No current work in progress, but this is something that we need to start working on. Any contribution on this would be greatly appreciated. :)

**Comment by sahin** [comment]
@digitalplaywright , @deepredsky has some suggestions . I would love to have mongo 5 support, because mongoid 4 has big problems in moped. We would love to move mongo 5 asap.

**Comment by sahin** [comment]
@digitalplaywright any news?

**Comment by mayatskiy** [comment]
Any updates?

**Comment by muhammett** [comment]
@digitalplaywright Any updates ?

**Comment by deepredsky** [comment]
I have added a patch. https://github.com/digitalplaywright/mongoid-slug/pull/186

**Comment by Nekromancer** [comment]
Still nothing?

**Comment by tzusman** [comment]
+1 please merge into the gem!

**Comment by muhammett** [comment]
+1

**Comment by dblock** [comment]
Closed via https://github.com/digitalplaywright/mongoid-slug/pull/187.
