### ISSUE TITLE
Release 5.0

### ISSUE THREAD

**Issue by dblock** [digitalplaywright/mongoid-slug#190]
Release 5.0 w/ mongoid 5 support.

@digitalplaywright Is the only one with RubyGems access ATM. Happy to do it if you add me.

**Comment by digitalplaywright** [comment]
I am good with releasing now. Closing out pull requests, like the index improvements, is something we can do for a future release.

**Comment by dblock** [comment]
Cool, thanks for RubyGems access. Take a look at/merge https://github.com/digitalplaywright/mongoid-slug/pull/191 and I'll cut a release.

**Comment by dblock** [comment]
Released.
