### ISSUE TITLE
Mongoid::Paranoia support documentation wrong!

### ISSUE THREAD

**Issue by ben-ole** [digitalplaywright/mongoid-slug#199]
The documentation in the Readme states the following:

    class Entity
      include Mongoid::Document
      include Mongoid::Slug
      include Mongoid::Paranoia
    end

MongoidSlug **stops working using the lines above!** Mongoid::Paranoia should be included before Mongoid::Slug:

    class Entity
      include Mongoid::Document
      include Mongoid::Paranoia
      include Mongoid::Slug
    end

**Comment by dblock** [comment]
This is clearly a bug. Could you build a test case to reproduce this? Happy to help fix.

**Comment by dblock** [comment]
I PRed a spec update in https://github.com/digitalplaywright/mongoid-slug/pull/200 that doesn't show that this is an issue.

**Comment by dblock** [comment]
I am going to close this, I believe it's fixed. Please reopen if there's still an issue, @ben-ole.
