### ISSUE TITLE
Slugs with different attributes for each locale?

### ISSUE THREAD

**Issue by alaouy** [digitalplaywright/mongoid-slug#213]
I used a method to generate localized slugs like this
 ```ruby
slug :generate_slug, localize: true
```
```ruby
def generate_slug
    "#{first_name} #{last_name} #{speciality} #{city}"
end
```
And I have a `first_name_ar` and `last_name_ar` attributes for the arabic version of the user's name, is there an option to use them to generate the arabic version of the slug?
Something that goes along the way of this :
```ruby
def generate_slug
   return "#{first_name_ar} #{last_name_ar} #{speciality} #{city}" if I18n.locale=="ar"
   "#{first_name} #{last_name} #{speciality} #{city}"
end
```

**Comment by dblock** [comment]
I think I am missing the point of your question - you can generate different slugs conditionally just like you did above. What would you like the actual slug used in the database to look like here? Are you generating an Arabic slug and getting a transliterated English result and that is the problem?

**Comment by alaouy** [comment]
@dblock the snippet that I proposed above does not work, it always gives the default behavior to  `"#{first_name} #{last_name} #{speciality} #{city}"` without taking into account the **locale**,.. I also encountred the problem that you mentioned, I always get the transliterated English result instead of the arabic slug.

**Comment by dblock** [comment]
Put some debug code in there, is the locale correct? There's no reason why that wouldn't work, maybe you want to provide a minimal piece of code that shows the output that we can run?

The transliterated English is built-in and is implemented in `UniqueSlug`, you would have to swap that out to do something else. Before we dig up how to do that, consider whether that's really what you want - UTF8 URLs don't read well, defeating most of the purpose of this library.

**Comment by alaouy** [comment]
@dblock Thanks for your help, I ended up using the same old links with juste some minor tweaks to show the page in the correct locale. closing this for now ...
