### ISSUE TITLE
How to enable to manually edit slugs for user?

### ISSUE THREAD

**Issue by bobur554396** [digitalplaywright/mongoid-slug#214]
Hi, I'm using this gem first time. I am using rails_admin gem in my CMS and I want to enable to change slugs in my Post modal. How can do this?

**Comment by dblock** [comment]
You should be able to assign `slugs = [ ... ]` (or `_slugs`, don't remember). If that doesn't work, it's a bug, reopen this and maybe write a spec (and maybe even a fix :)).
