### ISSUE TITLE
Support for Mongoid edge

### ISSUE THREAD

**Issue by Startouf** [digitalplaywright/mongoid-slug#216]
I am using Rails 5 with the "edge" Mongoid 

    https://github.com/estolfo/mongoid.git', branch: 'MONGOID-4218-rails-5'

including `Mongoid::Slug` generates a missing method error

> undefined local variable or method `scope_stack' for Company::Employee:Class

What can I do to fix/monkeypatch it ?

**Comment by dblock** [comment]
What version is mongoid edge reporting? You should fix it properly in all the instances in this gem where we check the mongoid version, this specific error comes from https://github.com/digitalplaywright/mongoid-slug/blob/be553527f1307f57e64457d206a0bb088c070dda/lib/mongoid/slug.rb#L171.

**Comment by Startouf** [comment]
I regularly update from this aforementionned branch, for Mongoid edge 6.0.0. Their last commit for the Rails-5 compatibility branch was last January

The final version of Mongoid 6.0 should be released somewhere mid-may according to Mongoid JIRA.

Thanks for the links. For now I'm leaving mongoid-slugs in standby in my app but if nothing have been done, in a couple I'll try to work on that and make a pull request.

**Comment by dblock** [comment]
I would appreciate a PR into https://github.com/dblock/mongoid-compatibility for mongoid 6 and then here for supporting mongoid#HEAD. All of the changes should be trivial from a cursory observation.

**Comment by Fudoshiki** [comment]
According to Mongoid JIRA, rekease in May 2017. We need monkey-path until this time.

**Comment by dblock** [comment]
Mongoid-compatibility 0.4.0 supports edge, please PR a change here that makes everything work out of the box.

**Comment by Fudoshiki** [comment]
mongoid_paranoia don't pass tests against Mongoid HEAD
https://github.com/simi/mongoid_paranoia/pull/43

**Comment by Fudoshiki** [comment]
@dblock We can close this

**Comment by Fudoshiki** [comment]
@dblock Should update changelog

**Comment by dblock** [comment]
Please @Fudoshiki ?

**Comment by dblock** [comment]
Generally mongoid-edge is a moving target, at this point it all works, so I am going to close this.

**Comment by Fudoshiki** [comment]
@dblock  What version? 5.2.1
