### ISSUE TITLE
Mongo::Error::OperationFailure: E11000 duplicate key error index: 

### ISSUE THREAD

**Issue by BorisBresciani** [digitalplaywright/mongoid-slug#222]
Hello

When I run the command:
`rake db:mongoid:create_indexes`

I get this error
`
Mongo::Error::OperationFailure: E11000 duplicate key error index: usernames_production.usernames.$_slugs_1  dup key: { : undefined } (11000)`

My model:

  `slug :name`
  `index({approve: 1})`

How to create indexes without this error thank you :)

Thx Boris

**Comment by dblock** [comment]
This shouldn't happen. Check what indexes you have on the collection, maybe there's a `slugs_1` index leftover from previous experiments? Do you think you can reproduce this in a spec? Maybe it's caused by `nil` entries in `name`?

**Comment by BorisBresciani** [comment]
Hello,

I'll see to make a spec, yes by cons I values (`name`) who are `nil`, it may be because of that?

**Comment by dblock** [comment]
You have a repro, you should be able to dig up why this is happening. Let us know if you need help. But either way it's trying to insert a duplicate value of `nil` into the collection for `name` and fails because there's already another entry with a `nil` value of `name` and there's a unique non-sparse index.

**Comment by BorisBresciani** [comment]
Thank you for your help, the problem is the values at `nil`, I put more value instead, for cons I do not see why the control point me to a duplication.

(sorry for my English)

**Comment by dblock** [comment]
Try to write a spec that reproduces this scenario?

**Comment by Dan-Nolan** [comment]
I can reproduce this in cases where stringex removes all the characters. Happened when a user tried to store `---` in a slug and stringex strips this down to an empty string

**Comment by BorisBresciani** [comment]
My website worked well and from one day to the next  I get this error:

`insertDocument :: caused by :: 11000 E11000 duplicate key error index: `

The error logs shows me nothing specific I can not see where have this error ...

**Comment by dblock** [comment]
I PRed a fix in #225.
