### ISSUE TITLE
undefined local variable or method `scope_stack' for Store:Class

### ISSUE THREAD

**Issue by sradu** [digitalplaywright/mongoid-slug#223]
I'm trying to run mongoid-slug with Rails 5 and 6.0.0.rc0 and it's returning:

NameError: undefined local variable or method `scope_stack' for Store:Class
	from /Users/john/.rvm/gems/ruby-2.2.5/gems/mongoid-slug-5.2.0/lib/mongoid/slug.rb:171:in `current_scope'
	from /Users/john/.rvm/gems/ruby-2.2.5/gems/mongoid-slug-5.2.0/lib/mongoid/slug.rb:145:in `queryable'
	from /Users/john/.rvm/gems/ruby-2.2.5/gems/mongoid-6.0.0.rc0/lib/mongoid/scopable.rb:212:in `with_default_scope'
	from /Users/john/.rvm/gems/ruby-2.2.5/gems/mongoid-6.0.0.rc0/lib/mongoid/findable.rb:159:in `last'
	from (irb):1

Will mongoid-slug work with mongoid 6?

**Comment by dblock** [comment]
This has been added in https://github.com/digitalplaywright/mongoid-slug/pull/219 and will be released with the next version, in the meantime use HEAD.
